// <auto-generated />
namespace Tab30.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RepairsV1Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RepairsV1Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060115003_RepairsV1Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
